name = "blackbox-api"
main = "index.ts"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "your-jwt-secret"
ALLOWED_EMAILS = "your@email.com,another@email.com"
GITHUB_TOKEN = "your-github-token"
GITHUB_REPO = "your-username/your-repo"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id" 